services:
  db:
    container_name: bearbasket-dev-db
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shopping_list
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  valkey:
    container_name: bearbasket-dev-valkey
    image: valkey/valkey:latest
    restart: always
    ports:
      - "6379:6379"

volumes:
  pgdata:
