services:
  dev:
    container_name: bearbasket-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    ports:
      - "3000:3000" # Web (Next.js)
      - "8000:8000" # Backend API (Axum)
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/shopping_list
      - REDIS_URL=redis://valkey:6379
    depends_on:
      - db
      - valkey
    stdin_open: true
    tty: true

  db:
    container_name: bearbasket-dev-db
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shopping_list
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  valkey:
    container_name: bearbasket-dev-valkey
    image: valkey/valkey:latest
    restart: always
    ports:
      - "6379:6379"

volumes:
  pgdata:
